### ISSUE TITLE
License and credits

### ISSUE THREAD

**Issue by nineinchnick** [borodulin/yii2-services#1]
I see this is based on the Yii 1 classes. Yii 1 is licensed under a [BSD license](http://www.yiiframework.com/license), I don't think you can just change it to MIT.

Also, it's important to include in the README what this is based on for two reasones:
- it's easier to check how much functionality is implemented
- it's not your own work, it's appropriate to credit the original author

Last question, from which Yii 1 version did you copy it? I personally made a few fixes that were included in the latest versions.

**Comment by borodulin** [comment]
You are right, I will change MIT to BSD.

This work is adaptation of Yii1 Web Services, you can read this in the README.
All original comments are present in source code, so you can see who is the author of every part of the code.
I used last Yii version, 1.1.15.

Thanks for yours comments.

**Comment by nineinchnick** [comment]
Oh sorry, I missed it. Maybe it should be mentioned again at the end under License section.

1.1.16 is the latest Yii 1 version.

**Comment by borodulin** [comment]
Ohh, I used 1.1.16, I just checked this.

**Comment by borodulin** [comment]
I have changed License to BSD.

http://stackoverflow.com/questions/1641804/how-to-modify-code-with-a-new-bsd-license
My code differs from original in adaptation for Yii2 framework, README.
It is not necessary to write this phrase in License header of every file, this is obviously by default.
